version: '3'
services:
  postgres:
    # Added this back
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=postgres_password
  redis:
    # Added this back
    image: 'redis:latest'
  client:
    image: 'rommelrico/complex-client'
    hostname: "client"
    deploy:
      resources:
        limits:
          memory: 128m
  api:
    image: "rommelrico/complex-server"
    hostname: "api"
    deploy:
      resources:
        limits:
          memory: 128m
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
#      - REDIS_HOST=$REDIS_HOST
#      - REDIS_PORT=$REDIS_PORT
#      - PGUSER=$PGUSER
#      - PGHOST=$PGHOST
#      - PGDATABASE=$PGDATABASE
#      - PGPASSWORD=$PGPASSWORD
#      - PGPORT=$PGPORT
  worker:
    image: "rommelrico/complex-worker"
    hostname: "worker"
    deploy:
      resources:
        limits:
          memory: 128m
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
#      - REDIS_HOST=$REDIS_HOST
#      - REDIS_PORT=$REDIS_PORT
  nginx:
    image: "rommelrico/complex-nginx"
    hostname: "nginx"
    deploy:
      resources:
        limits:
          memory: 128m
    ports:
      - '80:80'
