language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -f ./client/Dockerfile.dev -t rommelrico/complex-client-test ./client

script:
  - docker run -e CI=true rommelrico/complex-client-test npm run test -- --coverage src

after_success:
  - docker build -t rommelrico/complex-client ./client
  - docker build -t rommelrico/complex-nginx ./nginx
  - docker build -t rommelrico/complex-server ./server
  - docker build -t rommelrico/complex-worker ./worker
