version: "3.8"
services:
  mongodb:
    image: "mongo"
    container_name: "mongodb"
    volumes:
      - data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: rommeladmin
      MONGO_INITDB_ROOT_PASSWORD: secret
    # env_file:
      # - ./relative/path/to/file.env
    # networks:
      # - goals-net
  # backend:
  # frontend:

volumes:
  data:
