version: "3.8"
services:
  mongodb:
    image: "mongo"
    container_name: "mongodb"
    volumes:
      - data:/data/db
    # environment:
      # MONGO_INITDB_ROOT_USERNAME: rommeladmin
      # MONGO_INITDB_ROOT_PASSWORD: secret
    env_file:
      - ./env/mongo.env
    # networks:
      # - goals-net
  backend:
    build: ./backend
    # build:
      # context: ./backend
      # dockerfile: Dockerfile
      # docker build -t goals-node .
    ports:
      - "80:80"
    volumes:
      - ./backend:/app
      - logs:/app/logs
      - /app/node_modules
    env_file:
      - ./env/backend.env
    depends_on:
      - mongodb
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
    depends_on:
      - backend
    stdin_open: true
    tty: true

volumes:
  data:
  logs:
